In [5]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [9]:
a.ndim
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size


15

In [12]:
type(a)

numpy.ndarray

In [13]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

## Crearea array (tablouri) in numpy


In [16]:
c=np.array([2,3,4])
c

array([2, 3, 4])

In [17]:
c.dtype

dtype('int64')

In [18]:
d=np.array([1.2,3.4,5.3])
d.dtype

dtype('float64')

In [20]:
np.linspace(0,2, 9) #9 numere de la 0 la 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [1]:
%%timeit
list(range(10))
list(range(100))

100000 loops, best of 3: 3.56 µs per loop


In [2]:
%%bash
echo "Myshell is: " $SHELL
echo "My disk usage is: "
df -h

Myshell is:  /bin/bash
My disk usage is: 
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 984M     0  984M   0% /dev
tmpfs                    996M   27M  969M   3% /dev/shm
tmpfs                    996M  1.4M  995M   1% /run
tmpfs                    996M     0  996M   0% /sys/fs/cgroup
/dev/mapper/fedora-root   50G   36G   11G  77% /
tmpfs                    996M  672K  995M   1% /tmp
/dev/mapper/fedora-home  178G   69G  101G  41% /home
/dev/sda1                477M  212M  236M  48% /boot
tmpfs                    200M   16K  200M   1% /run/user/42
tmpfs                    200M   32K  200M   1% /run/user/1000


In [3]:
%%writefile test.txt
Aceasta este o fila text

Writing test.txt


In [4]:
!cat test.txt

Aceasta este o fila text

In [5]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3

In [8]:
enjoy = input('Va place Python?')
print('Raspuns: ', enjoy)

Va place Python?da


NameError: name 'da' is not defined

In [9]:
%qtconsole

In [11]:
import numpy
numpy.histogram

<function numpy.lib.function_base.histogram>

In [12]:
%%javascript
alert("Salut")

<IPython.core.display.Javascript object>

In [13]:
%%julia

ERROR:root:Cell magic `%%julia` not found.
