In [5]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [9]:
a.ndim
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size


15

In [12]:
type(a)

numpy.ndarray

In [13]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

## Crearea array (tablouri) in numpy


In [16]:
c=np.array([2,3,4])
c

array([2, 3, 4])

In [17]:
c.dtype

dtype('int64')

In [18]:
d=np.array([1.2,3.4,5.3])
d.dtype

dtype('float64')

In [20]:
np.linspace(0,2, 9) #9 numere de la 0 la 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])